server:
  port: ${PORT:52881}

management:
  tracing:
    enabled: true
    sampling.probability: 1.0 ## trace every call
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      roles: USER
      show-details: always
    env:
      show-values: ALWAYS
  server:
    port: ${ACTUATOR_PORT:52891}

logging:
  level:
    com.force.api: DEBUG
    com.vmware.sfdc.demo.accountservice: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

sfdc:
  service:
    unavailable: '{"status":503,"data": "Service currently unavailable."}'
  query:
    accounts: select account.id, account.name, account.type, (select contact.id, contact.lastname from account.contacts) from account
    opp_by_accts: select account.id, account.name, account.type, (select opportunity.id, opportunity.name, opportunity.type, opportunity.amount, opportunity.stagename, opportunity.closedate from account.opportunities) from account
    loadsql: select account.id, account.name, account.type, account.description, account.industry, account.ownership, account.website, account.phone, account.NumberOfEmployees, (select contact.id, contact.title, contact.department, contact.email, contact.name, contact.salutation, contact.phone, contact.mobilePhone, contact.firstName, contact.accountId, contact.lastname from account.contacts), (select opportunity.id, opportunity.name, opportunity.type, opportunity.amount, opportunity.stagename, opportunity.closedate, opportunity.description, opportunity.nextStep, opportunity.leadSource, opportunity.accountId from account.opportunities) from account

AUTHSERVICE_URL: http://localhost:52880
