server:
  port: ${PORT:52885}

spring:
  zipkin:
    enabled: false
  sleuth:
    enabled: false

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      roles: USER
      show-details: always
    env.show-values: ALWAYS

logging.level:
  com.vmware.sfdc.demo=: DEBUG
  # org.springframework.http.server.reactive: INFO
  # org.springframework.web.reactive: INFO
  # reactor.ipc.netty: INFO
  # reactor.netty: INFO
springdoc:
  swagger-ui.path: "/swagger-ui.html"
  api-docs.path: "/api-docs"

sfdc:
  authserviceURL: "http://localhost:52880/api"
  contactByAccounts: "select account.id, account.name, account.type, (select contact.id, contact.lastname from account.contacts) from account"
  opportunityByAccounts: "select account.id, account.name, account.type, (select opportunity.id, opportunity.name, opportunity.type, opportunity.amount, opportunity.stagename, opportunity.closedate from account.opportunities) from account"

---
spring:
  config:
    activate:
      on-profile: k8s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-83469100.okta.com/oauth2/aus7m6k7v5EdD4eoQ5d7/v1/keys
